### ISSUE TITLE
problem with install cvmfs

### ISSUE THREAD

**Issue by trustodia** [AAROC/CODE-RADE#123]
@brucellino I tried to use the install_cvmfs.sh and it showed 
ls: cannot access /cvmfs/apprepo.sagrid.ac.za: No such file or directory
/cvmfs/apprepo.sagrid.ac.za is not mounted. There was an error

**Comment by trustodia** [comment]
@brucellino this is still ocurring

**Comment by brucellino** [comment]
hi @trustodia - well - 1.5 years later I finally got around to this. Sorry :cry: 
This issue is no longer relevant, we've the deployment of CVMFS clients to https://github.com/AAROC/cvmfs-client-2.2
