### ISSUE TITLE
building centos7 shipit on ubuntu14.04

### ISSUE THREAD

**Issue by bazinski** [AAROC/CODE-RADE#190]

**Comment by bazinski** [comment]
https://ci.sagrid.ac.za/view/All/job/shipit/209/console
Assuming I am reading the console correctly.
It says its building the cento7 on ubuntu14.04 container ?

**Comment by brucellino** [comment]
Hi @bazinski you spotted something that is however not an "error'

All the shipit job does is pack up artefacts in /cvmfs into a tarball. This could be executed in a container based on any image - I chose the u1404 one, but it could have been anyone. 

The data is  in the volumes (this is why there's a `--volumes-from`).
