### ISSUE TITLE
gosia install

### ISSUE THREAD

**Issue by bazinski** [AAROC/CODE-RADE#206]
Gosia install together with Rachel a gui on top of it.
http://www-user.pas.rochester.edu/~gosia/mediawiki/index.php/Gosia
http://www-user.pas.rochester.edu/~gosia/mediawiki/index.php?title=Rachel_GUI&oldid=830

**Comment by brucellino** [comment]
@bazinski can you give a list of dependencies ?

**Comment by bazinski** [comment]
gosia simply depends on a fortran compiler.
Rachel a gui frontend : 
matplotlib pylab pygtk numpy pango
