### ISSUE TITLE
new jenkins build server

### ISSUE THREAD

**Issue by bazinski** [AAROC/CODE-RADE#208]
I am trying to get a new build server up at chpc.

I map port 9934 to port 22 on the "donated" host,
I was going to ask about where I find the public key for the jenkins user.

I however see that I am able to create a new key pair for each cloud deployed. 
Am I right ? 
So i dont need to use some global jenkins account to log into the slave host.

Will try later.

**Comment by brucellino** [comment]
Hey @bazinski Just checking if I understand this - you want a new build server, or  you want a new "cloud" ? IE, place to instantiate builds ? 

A new build server = a new jenkins instance. 

A new cloud = new docker/openstack endpoint on the _same_ build server, _ie_ ci.sagrid.ac.za.

I'm assuming you want a new cloud, right ? 

If I remember correctly from previous discussions, we were setting up a docker endpoint - see the screenshot 
![screenshot from 2017-11-10 10-03-08](https://user-images.githubusercontent.com/2115428/32650525-2b879008-c60f-11e7-96e2-e7da9ae84920.png)

The one in the screenshot is obviously localhost - you need to let me know the IP/port of the docker endpoint, and then we configure that cloud the same way as the local cloud.

**Comment by bazinski** [comment]
Ja cloud, my bad,
Its a docker end point via ssh.

I was wondering about the auth, but I saw when doing the add cloud thing that one can define the user auth there, so the private key for user jenkins is stored in the "additional cloud" somewhere and the public hence generated is then put on my node.
Does the user have to be jenkins or am I free to choose that as well ?

**Comment by brucellino** [comment]
> Its a docker end point via ssh.
Ah... no. It's a docker endpoint via HTTP, I think. That's the part where Jenkins talks to Docker to make new containers.

I think you're confusing that bit with the part where jenkins talks to the new container to start the build. _THAT_ happens over ssh or jnlp

**Comment by brucellino** [comment]
This issue was moved to http://discourse.sci-gaia.eu/t/new-jenkins-build-server/2664
