### ISSUE TITLE
Request: Pandas

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE#26]
Part of the SciPy stack.

**Comment by brucellino** [comment]
@smasoka, you reckon you'll be able to finish this by 16/10 ? if not, I'm moving this to FR2.

**Comment by smasoka** [comment]
@brucellino Yes we can still make it. 
Can I request a Jenkins job and repo

**Comment by brucellino** [comment]
I can't make the job until the repo is created in github. Can you make the repo at least (you don't need to commit any files yet)

**Comment by smasoka** [comment]
Repo created

**Comment by smasoka** [comment]
Pandas has dependencies
1. setuptools
2. Numpy 1.7.1 or higher
3. python-dateutil 1.5 or higher
4. pytz

**Comment by brucellino** [comment]
This issue was moved to http://discourse.sci-gaia.eu/t/request-pandas/2230
