### ISSUE TITLE
Request : install cvmfs script for Debian

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE#46]
the [install_cvmfs](cvmfs/install_cvmfs.sh) script only deals with CentOS. Propose to rename the script (and corresponding links in the READMEs) and add an `install_cvmfs_debian.sh` script to deal with other targets. Check the Ansible playbook for details on how to do this. I had to go the "compile CVMFS and install by hand" route, btw.

**Comment by smasoka** [comment]
Yes I am working on it, shortly it will be available. 
It will assume all dependencies are met for `cmake` in that debian system.

**Comment by brucellino** [comment]
yebo.
