### ISSUE TITLE
Use CODE-RADE Client VM via JSAGA

### ISSUE THREAD

**Issue by mtorrisi** [AAROC/CODE-RADE#62]
Hello,

I'm developing a simple portlet to use the CODE-RADE Client VM. This portlet submit a test job that perform the following script

```
#!/bin/sh 
#
# code-rade - portlet pilot script
#

## cvmfs stuff
# Environmental variables
export SITE=generic
export OS=u1404
export ARCH=x86_64
export CVMFS_DIR=/cvmfs/fastrepo.sagrid.ac.za

#load module
module use $CVMFS_DIR/modules/libraries
module use $CVMFS_DIR/modules/compilers
module avail
```

But I get the following in the stderr

```
pilot_script.sh: line 14: module: command not found
pilot_script.sh: line 15: module: command not found
pilot_script.sh: line 16: module: command not found
```

Thanks in advance.
Regards.

Mario

**Comment by brucellino** [comment]
Hi @mtorrisi.

If the package `environment-modules` is installed on the client, then check that the user's shell includes the modules setup script : 

```
. /etc/profile.d/modules.sh
```

before all the other stuff.

**Comment by mtorrisi** [comment]
Thanks @brucellino, I added `. /etc/profile.d/modules.sh` in the pilot script  and now I get module command.

**Comment by brucellino** [comment]
Great. I'm closing this and will add something to the documentation.
